In [1]:
from models_impute import *
from models_downstream import *
from baseline import *
import multiprocessing as mp
mp.set_start_method('spawn', force=True)

In [ ]:
data_arr, label_arr = Prepare_data('./data/', './static_tag.csv', 'ICUSTAY_ID', 'DIEINHOSPITAL')

In [3]:
model_params = {
    'num_levels': 6,
    'kernel_size': 6,
    'dilation_c': 4,
    }
model_data = parallel_impute(data_arr, cg, model_params)
model_data

NameError: name 'cg' is not defined

In [33]:
model_data

[array([[ 19.       ,   4.       ,  15.       , ..., 159.       ,
           3.2      ,  10.096519 ],
        [ 18.954546 ,   4.       ,  15.       , ..., 159.       ,
           3.1794753,  13.76515  ],
        [ 18.90909  ,   4.0176554,  15.       , ..., 159.       ,
           3.2      ,  20.561134 ],
        ...,
        [ 12.       ,   2.       ,   8.       , ..., 111.       ,
           3.6      , 137.58179  ],
        [ 12.       ,   2.       ,   8.       , ..., 111.       ,
           3.6      , 137.5899   ],
        [ 12.       ,   2.       ,   8.       , ..., 111.       ,
           3.6      , 137.60788  ]], dtype=float32),
 array([[ 16.       ,   4.       ,  15.       , ..., 233.       ,
           3.8      ,  11.054536 ],
        [ 16.       ,   4.       ,  15.       , ..., 233.       ,
           3.8      ,  13.221503 ],
        [ 16.       ,   4.       ,  15.       , ..., 233.       ,
           3.8      ,  15.287965 ],
        ...,
        [ 17.       ,   4.       ,  15.

In [12]:
train_and_evaluate(zero_data, label_arr, k=2, epochs=100, lr=0.02)


=== Fold 1/2 ===
Fold 1 Accuracy: 100.00%

=== Fold 2/2 ===
Fold 2 Accuracy: 100.00%


In [21]:
import os
import glob
import numpy as np
import pandas as pd

def load_csvs_as_numpy_array(directory):
    # 匹配目录下所有 .csv 文件
    csv_files = glob.glob(os.path.join(directory, '*.csv'))

    data_arrays = []
    for file in csv_files:
        df = pd.read_csv(file)      # 读取 CSV
        data = df.values            # 转为 NumPy 数组
        data_arrays.append(data)    # 加入列表

    return data_arrays  # 返回的是 list[np.ndarray]


In [22]:
np_arr = load_csvs_as_numpy_array('data')

In [23]:
np_arr

[array([[19.,  4., 15., ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]),
 array([[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]),
 array([[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]])]

In [4]:
cg = causal_discovery(np_arr, 3)

NameError: name 'np_arr' is not defined

In [ ]:
# cg = pd.DataFrame(cg)
cg = cg
print(type(cg))


In [ ]:
dat = pd.read_csv('data/200003.csv')
model_params = {
    'num_levels': 6,
    'kernel_size': 6,
    'dilation_c': 4,
    }
dat = dat.values  # 转为 NumPy 数组
dat = impute(dat, cg, model_params=model_params)


In [ ]:
re = mse_evaluate(dat, causal_matrix=cg)

In [ ]:
re

In [ ]:
dat2 = pd.read_csv('data/200007.csv')
model_params = {
    'num_levels': 6,
    'kernel_size': 6,
    'dilation_c': 4,
    }
dat2 = dat2.values  # 转为 NumPy 数组
dat2 = impute(dat2, cg, model_params=model_params)
re2 = mse_evaluate(dat2, causal_matrix=cg)
re2